import { COLORS } from './config';

export const PLAYER_SPELLS = [
  {
    id: 'bolt',
    key: 'Q',
    name: 'Arcane Bolt',
    icon: '⚡',
    damage: 150,
    manaCost: 30,
    cooldown: 600,
    speed: 10,
    radius: 9,
    color: COLORS.bolt,
    glowColor: COLORS.boltGlow,
    type: 'projectile',
    description: 'Fast arcane bolt',
  },
  {
    id: 'cannon',
    key: 'W',
    name: 'Void Cannon',
    icon: '💠',
    damage: 700,
    manaCost: 110,
    cooldown: 5000,
    speed: 5,
    radius: 20,
    color: COLORS.cannon,
    glowColor: COLORS.cannonGlow,
    type: 'projectile',
    description: 'Massive void orb',
  },
  {
    id: 'shield',
    key: 'E',
    name: 'Arcane Shield',
    icon: '🛡️',
    damage: 0,
    manaCost: 60,
    cooldown: 9000,
    speed: 0,
    radius: 0,
    color: COLORS.shield,
    glowColor: COLORS.shieldGlow,
    type: 'buff',
    duration: 5000,
    description: 'Blocks next attack',
  },
  {
    id: 'flash',
    key: 'R',
    name: 'Arcane Flash',
    icon: '✨',
    damage: 0,
    manaCost: 45,
    cooldown: 3500,
    speed: 0,
    radius: 0,
    color: COLORS.flash,
    glowColor: COLORS.flashGlow,
    type: 'buff',
    duration: 700,
    description: 'Brief invincibility',
  },
];

export const EXTRA_SPELLS = [
  {
    id: 'arcbolt',
    key: '⚡',
    name: 'Ark Işın',
    icon: '〰️',
    damage: 500,
    manaCost: 95,
    cooldown: 4500,
    speed: 0,
    radius: 0,
    color: '#22d3ee',
    glowColor: '#a5f3fc',
    type: 'beam',
    description: 'Zigzag ışın — anında hasar',
  },
];

export const BOSS_ATTACKS = [
  {
    id: 'voidBolt',
    damage: 120,
    speed: 4.5,
    radius: 14,
    color: COLORS.voidBolt,
    glowColor: COLORS.voidBoltGlow,
    type: 'single',
    phase2Only: false,
  },
  {
    id: 'darkWave',
    damage: 80,
    speed: 3.2,
    radius: 11,
    color: COLORS.darkWave,
    glowColor: COLORS.darkWaveGlow,
    type: 'spread',
    count: 4,
    spreadDeg: 55,
    phase2Only: false,
  },
  {
    id: 'enrageBeam',
    damage: 220,
    speed: 7,
    radius: 20,
    color: COLORS.enrageBeam,
    glowColor: COLORS.enrageGlow,
    type: 'single',
    phase2Only: true,
  },
];
